-- MySQL Script generated by MySQL Workbench
-- mié 14 jun 2023 17:06:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_suculent_photo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_suculent_photo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_suculent_photo` ;
USE `db_suculent_photo` ;

-- -----------------------------------------------------
-- Table `db_suculent_photo`.`sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_suculent_photo`.`sintoma` (
  `id_sintoma` VARCHAR(50) NOT NULL COMMENT 'este seria el nombre que recibe la carpeta, debe ser unico y sin espacios en blanco',
  `sintoma` VARCHAR(50) NOT NULL COMMENT 'descripcion del sintoma, el texto que se muestra para el usuario',
  `descripcion` VARCHAR(150) NOT NULL,
  `cantidad_consejos` INT NOT NULL,
  `cantidad_fotos` INT NOT NULL,
  PRIMARY KEY (`id_sintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_suculent_photo`.`consejo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_suculent_photo`.`consejo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NOT NULL,
  `id_sintoma` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consejo_sintoma_idx` (`id_sintoma` ASC),
  CONSTRAINT `fk_consejo_sintoma`
    FOREIGN KEY (`id_sintoma`)
    REFERENCES `db_suculent_photo`.`sintoma` (`id_sintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


--
-- Dumping data for table `sintoma`
--

LOCK TABLES `sintoma` WRITE;
/*!40000 ALTER TABLE `sintoma` DISABLE KEYS */;
INSERT INTO `sintoma` VALUES ('SALUDABLE','Saludable','La planta está en estado saludable',0,0);
/*!40000 ALTER TABLE `sintoma` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2023-06-24 13:05:47